# Generated by Django 4.2.3 on 2023-08-02 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('occupation', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('other', 'Other')], max_length=20)),
                ('roomType', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=10)),
                ('entryDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.DateField()),
                ('exit', models.DateField()),
                ('days', models.IntegerField()),
                ('occupant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pgmsApp.occupant')),
            ],
        ),
    ]
