# Generated by Django 4.2.3 on 2023-08-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgmsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitybill',
            name='entry',
        ),
    ]
